#!/bin/bash

NC='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
GRAY='\033[0;37m'
ROOT_DIR="$(pwd)"

[[ $# -gt 1 ]] && libraries="${*:2}" || libraries="Logs CAN/Raspberry XBee"

for lib in $libraries; do
  [[ ! -d "$lib" ]] && echo -e "${RED}Le dossier \"$lib\" n'existe pas${NC}" && continue
  [[ ! -f "$lib"/CMakeLists.txt ]] && echo -e "${RED}Le dossier \"$lib\" ne contient pas de librairie${NC}" && continue
done

case $1 in
  install|force-install)
    for lib in $libraries; do
      cd "$lib" || exit
      [[ -d build && $1 == "force-install" ]] && yes|rm -r build
      [[ ! -d build ]] && mkdir build

      cd build || exit
      cmake ..
      sudo make install && echo -e "${GREEN}La librairie \"$lib\" a été installée${NC}"

      cd "$ROOT_DIR" || exit
    done
  ;;

  pull|force-pull)
    for lib in $libraries; do
      cd "$lib" || exit
      [[ -d build && $1 == "force-pull" ]] && yes|rm -r build
      [[ ! -d build ]] && mkdir build

      cd build
      git pull
      cmake ..
      sudo make install && echo -e "${GREEN}La librairie \"$lib\" a été mise à jour${NC}"

      cd "$ROOT_DIR" || exit
    done
  ;;

  *)
    echo -e "${RED}Utilisation :${NC} lib_manager [install|force-install|pull|force_pull] ${GRAY}<...libs>${NC}"
    exit 1
  ;;
esac
